export const plantNames = [
    "Calathea_orbifolia",
    "Alocasia_longiloba",
    "Aloe_vera",
    "Bamboo",
    "Basil",
    "Begonia",
    "Cactus",
    "Carnation",
    "Cherry_blossom",
    "Chrysanthemum",
    "Clematis",
    "Crocus",
    "Daffodil",
    "Dandelion",
    "Eucalyptus",
    "Fern",
    "Ficus",
    "Fuchsia",
    "Geranium",
    "Hibiscus",
    "Hosta",
    "Hyacinth",
    "Hydrangea",
    "Iris",
    "Jasmine",
    "Lavender",
    "Lilac",
    "Lily",
    "Magnolia",
    "Mimosa",
    "Morning_glory",
    "Orchid",
    "Pansy",
    "Peony",
    "Petunia",
    "Poinsettia",
    "Poppy",
    "Rose",
    "Sage",
    "Snapdragon",
    "Snowdrop",
    "Spider_plant",
    "Succulent",
    "Sunflower",
    "Sweet_pea",
    "Tulip",
    "Wisteria",
    "Yarrow",
    "Yucca",
    "Zinnia",
    "African_violet",
    "Agave",
    "Amaryllis",
    "Azalea",
    "Bougainvillea",
    "Camellia",
    "Crocus",
    "Dahlia",
    "Dracaena",
    "Echeveria",
    "Fiddle_leaf_fig",
    "Gardenia",
    "Gerbera",
    "Golden_pothos",
    "Haworthia",
    "Jade_plant",
    "Kalanchoe",
    "Lantana",
    "Lithops",
    "Monstera_deliciosa",
    "Nerium",
    "Oxalis",
    "Pachira",
    "Ponytail_palm",
    "Rubber_plant",
    "Sansevieria",
    "Schefflera",
    "Snake_plant",
    "Tradescantia",
    "Umbrella_tree",
    "ZZ_plant"
  ];

  export async function determine() {
    const arr = []
    for (const plantString of plantNames) {
        const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${plantString}?redirect=false`;
        const response = await fetch(url)
        const data = await response.json()
        if (!data.extract.includes("may refer to:")){
            arr.push(plantString)
        }
    }
    return arr.length
  }